import { Day, NormalizedData, ScheduleOperation, ValidationIssue, CourseRequirement } from './types.js';
import { stableId } from './groupParser.js';
import { buildSharedSuggestions, explainIncompatibility, remapConstraints, sharedCompatibilitySignature } from './sharedCompatibility.js';
const slot=(d:Day,p:number)=>`${d}-${p}`;
const clone=<T>(x:T):T=>JSON.parse(JSON.stringify(x));
function deterministicSharedId(rs:CourseRequirement[]){return `shared_${stableId('req',rs.map(r=>r.id).sort().join('__'))}`}
export function validateOperation(data:NormalizedData,op:ScheduleOperation):ValidationIssue[]{const issues:ValidationIssue[]=[];const reqIds='requirementIds'in op?op.requirementIds:[];for(const id of reqIds)if(!data.requirements.some(r=>r.id===id))issues.push({level:'error',code:'operation-target-missing',message:`작업 대상 수업 ${id}을 찾을 수 없습니다.`});if(op.type==='set-period-only'&&op.periods.some(p=>p<1||p>8))issues.push({level:'error',code:'bad-period',message:'교시는 1-8 사이여야 합니다.'});if(op.type==='merge-shared-class'){const rs=op.requirementIds.map(id=>data.requirements.find(r=>r.id===id)).filter(Boolean) as CourseRequirement[];if(rs.length<2)issues.push({level:'error',code:'not-enough-targets',message:'두 개 이상 선택하세요.'});else{const msg=explainIncompatibility(data,rs);if(msg)issues.push({level:'error',code:'incompatible-merge',message:msg});const sigs=new Set(rs.map(r=>sharedCompatibilitySignature(data,r)));if(sigs.size!==1)issues.push({level:'error',code:'incompatible-merge-signature',message:'Merge rejected: compatibility signatures differ.'});}}return issues}
export function previewOperation(data:NormalizedData,op:ScheduleOperation):string[]{const errs=validateOperation(data,op);if(errs.length)return errs.map(e=>e.message);return[`${op.type} 작업이 ${'requirementIds'in op?op.requirementIds.length:0}개 항목에 적용됩니다.`]}
export function applyOperation(data:NormalizedData,op:ScheduleOperation):NormalizedData{const copy:NormalizedData=clone(data);const reqs=copy.requirements;const each=(fn:(id:string)=>void)=>{'requirementIds'in op&&op.requirementIds.forEach(fn)};if(validateOperation(copy,op).some(i=>i.level==='error'))return copy;if(op.type==='set-period-only')each(id=>{const r=reqs.find(x=>x.id===id)!;r.allowedSlots=['월','화','수','목','금'].flatMap(d=>op.periods.map(p=>`${d}-${p}`));r.afterSchool=op.periods.every(p=>p===8);copy.constraints.push({id:`con_period_${Date.now()}_${id}`,type:'period-only',targetRequirementIds:[id],value:{periods:op.periods},hard:true,source:'manual'});});if(op.type==='set-fixed-slot')each(id=>{const r=reqs.find(x=>x.id===id)!;r.fixedSlots=[slot(op.day,op.startPeriod)];copy.constraints.push({id:`con_fix_${Date.now()}_${id}`,type:'fixed-slot',targetRequirementIds:[id],value:{day:op.day,startPeriod:op.startPeriod,endPeriod:op.startPeriod},hard:true,source:'manual'});});if(op.type==='set-allowed-days')each(id=>{const r=reqs.find(x=>x.id===id)!;r.allowedSlots=op.days.flatMap(d=>[1,2,3,4,5,6,7,8].map(p=>slot(d,p)))});if(op.type==='set-teacher')each(id=>{const r=reqs.find(x=>x.id===id)!;r.teacherRule=op.teacherRule;r.teacherIds=op.teacherRule.type==='fixed'?op.teacherRule.teacherIds:[]});if(op.type==='merge-shared-class'){const rs=reqs.filter(r=>op.requirementIds.includes(r.id));if(rs.length){const base=clone(rs[0]);const newId=deterministicSharedId(rs);base.id=newId;base.cohortIds=[...new Set(op.cohortIds.length?op.cohortIds:rs.flatMap(r=>r.cohortIds))].sort();base.gradeIds=[...new Set(rs.flatMap(r=>r.gradeIds))].sort();base.sharedClass=true;base.shared=true;base.eventType='shared-class';base.sourceRequirementIds=rs.flatMap(r=>r.sourceRequirementIds??[r.id]);base.mergeMetadata={origin:'user',originalRequirements:clone(rs),originalConstraints:clone(copy.constraints.filter(c=>(c.targetRequirementIds??c.targetIds??[]).some(id=>op.requirementIds.includes(id))))};copy.constraints=remapConstraints(copy.constraints,op.requirementIds,newId);copy.requirements=[...reqs.filter(r=>!op.requirementIds.includes(r.id)),base];copy.diagnostics.sharedSuggestions=buildSharedSuggestions(copy);}}
if(op.type==='split-shared-class'){const idx=copy.requirements.findIndex(r=>r.id===op.sharedRequirementId);const r=copy.requirements[idx];if(idx>=0&&r?.mergeMetadata?.origin==='user'){const originals=clone(r.mergeMetadata.originalRequirements);const originalIds=new Set(originals.map(x=>x.id));copy.requirements.splice(idx,1,...originals);copy.constraints=copy.constraints.filter(c=>!(c.targetRequirementIds??c.targetIds??[]).includes(r.id));copy.constraints=remapConstraints([...copy.constraints,...clone(r.mergeMetadata.originalConstraints)],[],r.id).filter(c=>(c.targetRequirementIds??c.targetIds??[]).every(id=>id===r.id||originalIds.has(id)||copy.requirements.some(req=>req.id===id)));copy.diagnostics.sharedSuggestions=buildSharedSuggestions(copy);}else copy.warnings.push({level:'warning',code:'split-manual',message:`${op.sharedRequirementId} 공동수업 원본을 찾을 수 없습니다.`});}return copy}
export function undoOperation(_before:NormalizedData,after:NormalizedData):NormalizedData{return clone(after)}
