export type Day='월'|'화'|'수'|'목'|'금';
export interface TimeSlot{day:Day;period:number;startTime:string;endTime:string;type:'arrival'|'class'|'lunch'|'after-school'}
export interface SourceReference{sheetName:string;headerRow:number;startColumn:number;sourceRow?:number;sourceCells?:string[]}
export interface Student{id:string;name:string;gradeId:string;enrollments:string[];exclusions:string[]}
export interface GradeGroup{id:string;name:string;memberGradeIds:string[];studentIds:string[];source?:SourceReference}
export interface Cohort{id:string;name:string;gradeIds:string[];studentIds:string[]}
export interface Teacher{id:string;name:string;aliases:string[];availability?:string[];unavailableSlots:string[];preferredSlots:string[];maximumDailyPeriods?:number}
export interface Subject{id:string;name:string;aliases:string[];defaultRoomId?:string;color?:string}
export type EventType='normal-class'|'shared-class'|'grade-only'|'teacher-only'|'school-wide'|'fixed-event'|'after-school';
export type ConstraintType='fixed-slot'|'allowed-slots'|'forbidden-slots'|'after-school-only'|'teacher-unavailable'|'room-required'|'consecutive'|'different-days'|'locked-assignment';
export interface ScheduleConstraint{id:string;type:ConstraintType;targetIds:string[];value:unknown;hard:boolean;source:'excel'|'manual'|'ai'}
export interface CourseRequirement{id:string;subjectId:string;gradeIds:string[];cohortIds:string[];teacherIds:string[];totalPeriodsPerWeek:number;meetingsPerWeek:number;meetingLengths:number[];roomId?:string;fixedSlots:string[];allowedSlots:string[];forbiddenSlots:string[];preferredSlots:string[];consecutive:boolean;afterSchool:boolean;sharedClass:boolean;eventType:EventType;priority:number;source?:SourceReference;status?:'ready'|'needs-mapping'|'error';issues?:string[]}
export interface Room{id:string;name:string;capacity?:number;availability?:string[]}
export interface ImportDiagnostics{sheetRanges:Record<string,{rows:number;columns:number}>;headers:Array<{sheetName:string;headerRow:number;startColumn:number;kind:'student'|'grade'|'teacher'|'allocation';headers:string[]}>;gradeBlocks:Array<{sheetName:string;headerRow:number;startColumn:number;gradeName:string}>;teacherBlocks:Array<{sheetName:string;headerRow:number;startColumn:number;teacherName:string}>;skippedBlocks:Array<{sheetName:string;headerRow:number;startColumn:number;reason:string}>;detectedSubjectCount:number;detectedRequirementCount:number;allocationTeacherAliases:string[];needsMapping:string[]}
export interface NormalizedData{students:Student[];grades:GradeGroup[];cohorts:Cohort[];teachers:Teacher[];subjects:Subject[];requirements:CourseRequirement[];constraints:ScheduleConstraint[];rooms:Room[];timeSlots:TimeSlot[];warnings:ValidationIssue[];errors:ValidationIssue[];sourceSheets:string[];diagnostics:ImportDiagnostics}
export interface ValidationIssue{level:'error'|'warning';code:string;message:string;context?:Record<string,string|number|boolean>}
export interface ClassInstance{id:string;requirementId:string;subjectId:string;gradeIds:string[];cohortIds:string[];studentIds:string[];teacherIds:string[];roomId?:string;length:number;fixedStart?:SlotKey;afterSchool:boolean;locked?:boolean}
export type SlotKey=`${Day}-${number}`;
export interface Assignment{instanceId:string;slot:SlotKey;length:number;subjectId:string;gradeIds:string[];cohortIds:string[];studentIds:string[];teacherIds:string[];roomId?:string;locked?:boolean}
export interface SolveOptions{maxNodes:number;maxSeconds:number;seed:number;allowUnassigned:boolean;weights:Record<string,number>}
export interface SolveProgress{elapsedMs:number;nodes:number;backtracks:number;assigned:number;total:number;unassigned:number;bestScore:number;reason:string}
export interface SolveResult{assignments:Assignment[];unassigned:ClassInstance[];issues:ValidationIssue[];progress:SolveProgress;score:number}
