export type Day='월'|'화'|'수'|'목'|'금';
export interface TimeSlot{day:Day;period:number;startTime:string;endTime:string;type:'arrival'|'class'|'lunch'|'after-school'}
export interface Student{id:string;name:string;gradeId:string;enrollments:string[];exclusions:string[]}
export interface GradeGroup{id:string;name:string;memberGradeIds:string[];studentIds:string[]}
export interface Teacher{id:string;name:string;aliases:string[];availability?:string[];unavailableSlots:string[];preferredSlots:string[];maximumDailyPeriods?:number}
export interface Subject{id:string;name:string;aliases:string[];defaultRoomId?:string;color?:string}
export type EventType='normal-class'|'shared-class'|'grade-only'|'teacher-only'|'school-wide'|'fixed-event'|'after-school';
export interface CourseRequirement{id:string;subjectId:string;gradeIds:string[];teacherIds:string[];totalPeriodsPerWeek:number;meetingsPerWeek:number;meetingLengths:number[];roomId?:string;fixedSlots:string[];allowedSlots:string[];forbiddenSlots:string[];preferredSlots:string[];consecutive:boolean;afterSchool:boolean;sharedClass:boolean;eventType:EventType;priority:number}
export interface Room{id:string;name:string;capacity?:number;availability?:string[]}
export interface NormalizedData{students:Student[];grades:GradeGroup[];teachers:Teacher[];subjects:Subject[];requirements:CourseRequirement[];rooms:Room[];timeSlots:TimeSlot[];warnings:ValidationIssue[];errors:ValidationIssue[];sourceSheets:string[]}
export interface ValidationIssue{level:'error'|'warning';code:string;message:string;context?:Record<string,string|number|boolean>}
export interface ClassInstance{id:string;requirementId:string;subjectId:string;gradeIds:string[];teacherIds:string[];roomId?:string;length:number;fixedStart?:SlotKey;afterSchool:boolean;locked?:boolean}
export type SlotKey=`${Day}-${number}`;
export interface Assignment{instanceId:string;slot:SlotKey;length:number;subjectId:string;gradeIds:string[];teacherIds:string[];roomId?:string;locked?:boolean}
export interface SolveOptions{maxNodes:number;maxSeconds:number;seed:number;allowUnassigned:boolean;weights:Record<string,number>}
export interface SolveProgress{elapsedMs:number;nodes:number;backtracks:number;assigned:number;total:number;unassigned:number;bestScore:number;reason:string}
export interface SolveResult{assignments:Assignment[];unassigned:ClassInstance[];issues:ValidationIssue[];progress:SolveProgress;score:number}
