import "./styles.css";
import {importClasses,importConstraints,populatedConstraintTemplate} from './importer.js'; import {solve} from './solver.js'; import {DAYS,GRADES,TEACHERS,TIMES,ImportData,SolveResult} from './model.js';
let data:ImportData|null=null,result:SolveResult|null=null; const app=document.getElementById('app')!; const read=(f:File)=>f.text();
function stat(k:string,v:any){return `<div class=card><b>${k}</b><strong>${v}</strong></div>`}
function render(){app.innerHTML=`<header><h1>Chronos Scheduler</h1><p>CSV-first MILP scheduler. Class rows are atomic shared classes; 수업 ID is opaque.</p></header><main><section class=panel><h2>Import CSVs</h2><input id=classes type=file accept=.csv><input id=constraints type=file accept=.csv><button id=template ${data?'':'disabled'}>Download populated constraint template</button></section>${data?review():''}${result?results():''}</main>`; bind();}
function review(){const s=data!.stats,c=data!.constraints; return `<section class=panel><h2>Import Review</h2><div class=grid>${stat('class rows imported',s.classRows)}${stat('subjects',s.subjects)}${stat('canonical grades',s.canonicalGrades)}${stat('named teachers',s.namedTeachers)}${stat('rooms',s.rooms)}${stat('inferred meetings',s.meetings)}${stat('total period units',s.periodUnits)}${stat('consecutive blocks',s.consecutiveBlocks)}${stat('after-school class rows',s.afterSchoolRows)}${stat('after-school meeting periods',s.afterSchoolPeriods)}${stat('active constraints',(c?.activeStrict??0)+(c?.activeAvailability??0))}${stat('excluded constraint rows',c?.excluded.length??0)}${stat('validation errors',data!.errors.length)}${stat('warnings',data!.warnings.length+(c?.warnings.length??0))}</div>${c?.warnings.map(w=>`<p class=warn>${w}</p>`).join('')??''}${c?.excluded.length?'<button id=continue>Continue without unmatched constraint rows</button>':''}<button id=generate ${data!.errors.length?'disabled':''}>Generate</button><h3>Grade loads</h3><table><tbody>${GRADES.map(g=>`<tr><td>${g}</td><td>${s.gradeLoads[g].regular} regular</td><td>${s.gradeLoads[g].after} period-8</td></tr>`).join('')}</tbody></table><h3>Normalized Classes</h3><table><thead><tr><th>ID</th><th>subject</th><th>original grade expression</th><th>expanded grades</th><th>teacher semantics</th><th>room</th><th>weekly</th><th>generated meeting pattern</th><th>period type</th><th>preference</th></tr></thead><tbody>${data!.classes.map(x=>`<tr><td>${x.id}</td><td>${x.subject}</td><td>${x.gradeExpr}</td><td>${x.grades.join(', ')}</td><td>${x.teacher.kind==='co'?'Both teachers are required and will be occupied simultaneously.':x.teacherCell}</td><td>${x.room}</td><td>${x.weekly}</td><td>${x.meetings.map(m=>m.length+' period').join(' + ')}</td><td>${x.afterSchool?'after-school':'regular'}</td><td>${x.morning?'morning':x.afternoon?'afternoon':'none'}</td></tr>`).join('')}</tbody></table></section>`}
function cell(a:any){return `${a.subject}<br><small>${a.teacher}</small>`} function table(filter:(a:any)=>boolean){return `<table class=schedule><thead><tr><th>Period</th><th>Time</th>${DAYS.map(d=>`<th>${d}</th>`).join('')}</tr></thead><tbody>${[1,2,3,4,5,6,7,8].map(p=>`<tr><th>${p}</th><td>${TIMES[p]}</td>${DAYS.map(d=>{const a=result!.assignments.find(x=>filter(x)&&x.day===d&&p>=x.start&&p<x.start+x.length);return `<td>${a?cell(a):''}</td>`}).join('')}</tr>`).join('')}</tbody></table>`}
function results(){const r=result!,d=r.diagnostics; return `<section class=panel><h2>Results</h2><div class=grid>${stat('solver status',r.status)}${stat('elapsed time',r.elapsedMs+' ms')}${stat('variable count',r.variableCount)}${stat('constraint count',r.constraintCount)}${stat('objective value',r.objectiveValue)}${stat('preference violations',r.preferenceViolations)}${stat('assigned meetings',`${r.assignments.length}/${data!.stats.meetings}`)}${stat('hard conflicts',d.gradeConflicts+d.teacherConflicts+d.roomConflicts)}</div><h3>Grade timetables</h3>${GRADES.map(g=>`<details open><summary>${g}</summary>${table(a=>a.grades.includes(g))}</details>`).join('')}<h3>Teacher timetables</h3>${TEACHERS.map(t=>`<details><summary>${t}</summary>${table(a=>a.teachers.includes(t))}</details>`).join('')}<h3>Room timetables</h3>${[...new Set(data!.classes.map(c=>c.room))].map(room=>`<details><summary>${room}</summary>${table(a=>a.room===room)}</details>`).join('')}<h3>Master timetable</h3>${table(()=>true)}<button id=export>Export XLSX</button></section>`}
function bind(){document.getElementById('classes')?.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0]; if(f){data=importClasses(await read(f)); result=null; render();}}); document.getElementById('constraints')?.addEventListener('change',async e=>{const f=(e.target as HTMLInputElement).files?.[0]; if(f&&data){data.constraints=importConstraints(await read(f),data.classes); render();}}); document.getElementById('generate')?.addEventListener('click',()=>{if(data){result=solve(data); render();}}); document.getElementById('continue')?.addEventListener('click',()=>alert('Unmatched constraint rows excluded.')); document.getElementById('template')?.addEventListener('click',()=>{if(!data)return; download('populated_constraints.csv',populatedConstraintTemplate(data.classes),'text/csv')}); document.getElementById('export')?.addEventListener('click',()=>download('schedule.xlsx',JSON.stringify({data,result},null,2),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'));}
function download(name:string,content:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();}
render();
