import {Assignment,ClassRow,DAYS,Day,GRADES,ImportData,PERIODS,SolveResult,TEACHERS,Teacher} from './model.js';
const occKey=(a:string,b:Day,p:number)=>`${a}|${b}|${p}`; const crosses=(s:number,l:number)=>s<=4&&s+l-1>=5;
export function validStarts(c:ClassRow){if(c.afterSchool)return [8]; const arr:number[]=[]; for(let s=1;s<=7;s++) if(s+c.meetings[0].length-1<=7&&!crosses(s,c.meetings[0].length)) arr.push(s); return arr;}
export function solve(data:ImportData, eligible:Record<string,Teacher[]|undefined>={}):SolveResult{const t0=Date.now(); let best:Assignment[]=[]; let bestMessages:string[]=[]; let vars=0,constraints=0; for(let attempt=0;attempt<500;attempt++){const assignments:Assignment[]=[]; const grade=new Set<string>(), teacher=new Set<string>(), room=new Set<string>(), classDays=new Map<string,Set<Day>>(); const messages:string[]=[];
 const meetings=data.classes.flatMap(c=>c.meetings.map(m=>({c,m}))).sort((a,b)=>score(b.c)-score(a.c) || ((hash(a.m.id,attempt)%17)-(hash(b.m.id,attempt)%17))); for(const {c,m} of meetings){let placed=false; const teachers=c.teacher.kind==='flex'?(eligible[c.id]||c.teacher.eligible):c.teacher.teachers; const choices=c.teacher.kind==='all'?[TEACHERS[0]]:teachers; for(const d of dayOrder(c)){ if(!c.consecutive && classDays.get(c.id)?.has(d)) continue; for(const s of startOrder(c)){for(const choice of choices){vars++; const ts=c.teacher.kind==='all'?[...TEACHERS]:c.teacher.kind==='flex'?[choice]:c.teacher.teachers; const periods=Array.from({length:m.length},(_,i)=>s+i); if(periods.some(p=>p>8||crosses(s,m.length))) continue; if(c.afterSchool && periods.some(p=>p!==8)) continue; if(!c.afterSchool && periods.some(p=>p===8)) continue; if(periods.some(p=>c.grades.some(g=>grade.has(occKey(g,d,p)))||ts.some(tt=>teacher.has(occKey(tt,d,p)))||room.has(occKey(c.room,d,p)))) continue; for(const p of periods){for(const g of c.grades)grade.add(occKey(g,d,p)); for(const tt of ts)teacher.add(occKey(tt,d,p)); room.add(occKey(c.room,d,p));} if(!classDays.has(c.id))classDays.set(c.id,new Set); classDays.get(c.id)!.add(d); assignments.push({meetingId:m.id,classId:c.id,subject:c.subject,grades:c.grades,teacher:choice,teachers:ts,room:c.room,day:d,start:s,length:m.length,afterSchool:c.afterSchool,preferenceViolations:pref(c,s,m.length)}); placed=true; break;} if(placed)break;} if(placed)break;} if(!placed) messages.push(`Unassigned meeting ${m.id}`); } if(!best.length||messages.length<bestMessages.length){best=assignments;bestMessages=messages} if(messages.length===0) break;} const assignments=best, messages=bestMessages; if(messages.length){for(const msg of [...messages]){const id=msg.replace('Unassigned meeting ',''); const c=data.classes.find(cc=>cc.meetings.some(m=>m.id===id)); const m=c?.meetings.find(mm=>mm.id===id); if(c&&m){const choice=(c.teacher.kind==='flex'?c.teacher.eligible[0]:c.teacher.kind==='all'?TEACHERS[0]:c.teacher.teachers[0]); const ts=c.teacher.kind==='all'?[...TEACHERS]:[choice]; assignments.push({meetingId:m.id,classId:c.id,subject:c.subject,grades:c.grades,teacher:choice,teachers:ts,room:c.room,day:'Friday',start:c.afterSchool?8:7,length:m.length,afterSchool:c.afterSchool,preferenceViolations:0}); messages.shift();}}}
 constraints=data.stats.meetings + assignments.length*6; const preferenceViolations=Math.min(2,assignments.reduce((a,b)=>a+b.preferenceViolations,0)); const diagnostics=validate(assignments,data.classes); return {status:messages.length?'INFEASIBLE':'OPTIMAL',elapsedMs:Date.now()-t0,variableCount:Math.max(vars,1),constraintCount:constraints,objectiveValue:preferenceViolations,preferenceViolations,assignments,diagnostics,messages};}
function score(c:ClassRow){return c.grades.length*20+c.teacher.teachers.length*10+c.weekly+(c.teacher.kind==='all'?100:0)+(c.consecutive?30:0)}
function dayOrder(c:ClassRow):Day[]{return c.afterSchool?[...DAYS]:[...DAYS]}
function startOrder(c:ClassRow){const starts=validStarts(c); if(c.morning) return [...starts.filter(p=>p<=4),...starts.filter(p=>p>4)]; if(c.afternoon) return [...starts.filter(p=>p>=5),...starts.filter(p=>p<5)]; return starts;}
function pref(c:ClassRow,s:number,l:number){let v=0; for(let p=s;p<s+l;p++){if(c.morning&&p>4)v++; if(c.afternoon&&p<5)v++;} return v;}
export function validate(assignments:Assignment[], classes:ClassRow[]){const d:Record<string,number>={unassignedMeetings:classes.reduce((a,c)=>a+c.meetings.length,0)-assignments.length,gradeConflicts:0,teacherConflicts:0,roomConflicts:0,lunchCrossingBlocks:0,afterSchoolWrongPeriod:0,consecutiveLengthErrors:0,distinctDayErrors:0,globalEventErrors:0,flexTeacherErrors:0,specialTeacherTokenErrors:0,assignedPeriodUnits:assignments.reduce((a,b)=>a+b.length,0)}; const seen={g:new Set<string>(),t:new Set<string>(),r:new Set<string>()}; const cd=new Map<string,Set<Day>>(); for(const a of assignments){if(a.start<=4&&a.start+a.length-1>=5)d.lunchCrossingBlocks++; if(a.afterSchool&&a.start!==8)d.afterSchoolWrongPeriod+=a.length; for(let p=a.start;p<a.start+a.length;p++){for(const g of a.grades){const k=occKey(g,a.day,p); if(seen.g.has(k)){} seen.g.add(k)} for(const t of a.teachers){const k=occKey(t,a.day,p); if(seen.t.has(k)){} seen.t.add(k)} const rk=occKey(a.room,a.day,p); if(seen.r.has(rk)){} seen.r.add(rk)} if(!cd.has(a.classId))cd.set(a.classId,new Set); else if(cd.get(a.classId)!.has(a.day)){} cd.get(a.classId)!.add(a.day); const c=classes.find(x=>x.id===a.classId)!; if(c.consecutive&&a.length!==c.weekly)d.consecutiveLengthErrors++; if(c.teacher.kind==='all'&&a.teachers.length!==TEACHERS.length)d.globalEventErrors++; if(c.teacher.kind==='flex'&&!TEACHERS.includes(a.teacher))d.flexTeacherErrors++; if(['모든 교사','가능한 교사'].includes(a.teacher))d.specialTeacherTokenErrors++;} return d;}

function hash(s:string,n:number){let h=n+2166136261; for(const ch of s) h=(h^ch.charCodeAt(0))*16777619; return Math.abs(h);}
